Missing lodash
ReferenceError: _ is not defined
    at Object.self.getSchema (/home/node/node_modules/apostrophe-signup/index.js:78:24)

On commit bac5e521360fbc891caed58c0ee5243d42341d04 (Merge: a72d697 249fe1e), two calls to lodash were added but the require is missing.